im:
  tcpPort: 9000
  webSocketPort: 19000
  bossThreadSize: 1
  workThreadSize: 8
  hearBertTimeOut: 3000 #单位毫秒
  redis:
    mode: single # 单机模式：single 哨兵模式：sentinel 集群模式：cluster
    database: 0
    password:
    timeout: 3000 # 超时时间
    poolMinIdle: 8 #最小空闲数
    poolConnTimeout: 3000 # 连接超时时间(毫秒)
    poolSize: 10 # 连接池大小
    single: #redis单机配置
      address: 42.193.140.45:6378
  rabbitmq:
    host: 42.193.140.45
    port: 5672
    virtualHost: /
    userName: guest
    password: guest
  zkConfig:
    zkAddr: 127.0.0.1:2181
    zkConnectTimeOut: 5000

